media_homepage:
    path:  /
    defaults: { _controller: StudioEchoMediaBundle:UploadMedia:index, culture: 'fr' }

# Upload / Display routes
media_display_zone:
    path:  /display/{mediaObjectId}/key/{mediaParameterConfigKey}/{culture}
    defaults: { _controller: StudioEchoMediaBundle:UploadMedia:displayZone, culture: 'fr' }

# JSON routes
media_upload_file:
    path:  /upload-file/upload.{_format}
    defaults: { _controller: StudioEchoMediaBundle:UploadMedia:upload, _format: json }
    requirements: { _format: (xml|json) }

media_delete_file:
    path: /delete-file/{mediaFileId}/{mediaParameterConfigKey}/delete.{_format}
    defaults: { _controller: StudioEchoMediaBundle:UploadMedia:delete, _format: json }
    requirements: { _format: (xml|json), _method: GET }

media_online_file:
    path: /online-file/{mediaFileId}//{culture}/online.{_format}
    defaults: { _controller: StudioEchoMediaBundle:UploadMedia:online, _format: json, culture: 'fr' }
    requirements: { _format: (xml|json), _method: GET }

media_edit_file:
    path: /edit-file/{mediaFileId}/{culture}/edit.{_format}
    defaults: { _controller: StudioEchoMediaBundle:UploadMedia:edit, _format: json, culture: 'fr' }
    requirements: { _format: (xml|json), _method: POST }

media_sort:
    path: /sort-files/sort.{_format}
    defaults: { _controller: StudioEchoMediaBundle:UploadMedia:sort, _format: json }
    requirements: { _format: (xml|json), _method: POST }
